### ISSUE TITLE
contracts points to a wrong link after a snap refresh

### ISSUE THREAD

**Issue by linggao** [open-horizon/bluehorizon-snap#19]
snap install --devmode --revision 52 bluehorizon
snap refresh --devmode --beta bluehorizon   (beta is revision 55).
ls -l /var/snap/bluehorizon/55/go/src/github.com/open-horizon/go-solidity/
lrwxrwxrwx 1 root root 30 Jan 27 19:00 contracts -> /snap/bluehorizon/52/contracts
Please note that contracts points /snap/bluehorizon/**52**/contracts instead of /snap/bluehorizon/**55**/contracts

**Comment by linggao** [comment]
PR https://github.com/open-horizon/bluehorizon-snap/pull/20

**Comment by cgiroua** [comment]
I have verified a snap refresh now properly links the contracts to the new snap revision, thanks!
