### ISSUE TITLE
Automated build/deployment

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/bluehorizon-snap#22]

**Comment by michaeldye** [comment]
I outlined a possible snap release tool design once. What do you think?

- user executes script "release" (in bluehorizon-snap repo) like this:
   ./release "channel_name"

- operations:
0. check for "grade" in snapcraft.yaml; if it's "stable", require source-tag on all parts' github sources
1. if specified "stable" or "candidate" channel and source-tag versions don't exist or don't match snapcraft's specified version, exit with error (ensures we don't build stable releases out of master)
2. TODO: check creds on all repos, softlayer objectstore
  3. push bluehorizon content to launchpad git (it's stored separately from github)
  4. If stable, CI in launchpad checks for existing release version in channel(s), exits with error instructing to delete from snap store
  5. does release; CI writes a "release" doc to RO part of snap w/ timestamp, version info, etc.
  6. TODO: locally-executed release script waits, polling for new release to snap repo. On success, checks release stamp in snap. Pushes backup snap to objectstore
</pre>

**Comment by michaeldye** [comment]
The CI for releasing snaps can be done by launchpad, https://launchpad.net/bluehorizon-snap . The tool mentioned would use that system for releases.

**Comment by bmpotter** [comment]
Looks good, thx for writing this up. This is probably a stupid question, but if we are writing a release script, what value do we get from launchpad?

**Comment by bmpotter** [comment]
mostly dup of https://github.com/open-horizon/horizon-deb-packager/issues/58
