### ISSUE TITLE
horizon-pi3-2017-02-16_0010 rpi3 onboard wifi not working

### ISSUE THREAD

**Issue by datajerk** [open-horizon/bluehorizon-snap#34]
title says it all

**Comment by datajerk** [comment]
Here's the fix:

Add to your build script for the flash image:
```
cd /lib/firmware/brcm/
wget https://raw.githubusercontent.com/RPi-Distro/firmware-nonfree/master/brcm80211/brcm/brcmfmac43430-sdio.txt
```

**Comment by linggao** [comment]
Built a new image with the above instructions. http://1dd40.http.tor01.cdn.softlayer.net/colonus/horizon-pi3-2017-02-21_1327.img.zip
