### ISSUE TITLE
Document how to manually set device id before registration

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/bluehorizon-snap#48]
This is needed for a partner demo in which they want their own map.

**Comment by linggao** [comment]
For pi2 and pi3:  for the running bluehorizon, to change the device id:
```
vi /var/snap/bluehorizon/common/config/device_id  #make modification
systemctl restart snap.bluehorizon.anax.service
```

For pi2 and pi3, if the bluehorizon is removed, to change the device id:
 ```
/var/horizon/config/device_id  # make modificatin
/usr/local/sbin/horizon-configure
snap install --devmode --beta bluehorizon
```

FOr x86, use the same proceduure

**Comment by linggao** [comment]
For pi2 and pi3 with raspbian image:  for the running bluehorizon, to change the device id:
```
# make modification for the existing device id
vi /opt/hzn_common/config/device_id  

# save it for persistence
cp /opt/hzn_common/config/device_id /var/horizon/config/device_id

# restart the anax
systemctl restart bluehorizon.anax.service
```

For pi2 and pi3 with raspbianimage: if the bluehorizon.anax.service is not running, to change the device id:
 ```
# make modification
vi /var/horizon/config/device_id  

# following script copies the device_id and other configuration to  /opt/hzn_common/
/usr/local/sbin/horizon-configure

# start the anax
systemctl start bluehorizon.anax.service
```

**Comment by bmpotter** [comment]
For enabling users to set device-id prefix, i see 4 options that vary in difficulty of implementation and usability:

1. Maintain a separate pi2 & pi3 image that automatically sets the device_id file above with the correct prefix.
1. Provide instructions to device owner about setting the device_id file in the boot partition of the sd card
1. Provide instructions to device owner about setting the device_id file after the pi has booted, and then restart anax, before registering.
1. Have reg UI allow the device owner to set the device id (or just a prefix for it). (And under the covers it either restarts anax or add the ability to anax to accept a new device-id at that point.)
